"""Deterministic template compiler for gold marts (Module 13 §5.2) — turns a closed
vocabulary (metric_column, aggregation, dimension_columns, time_column, time_grain) into a
`SELECT ... GROUP BY` string. No SQL is ever generated by Mistral for gold; this is the only
thing that writes gold SQL, exactly like `superset_templates.py` is the only thing that turns
an indicator spec into a Superset chart payload.

Module 14 extension "primitives gold" — three additive, closed-vocabulary primitives layered
on top of the original flat contract (metric_column + aggregation), unblocking a class of KPI
the flat contract can't express (filtered counts, ratios, derived date-difference measures):
FILTER_OPS (§3.1), aggregation="RATIO" with numerator/denominator (§3.2), and metric=date_diff
(§3.3, replacing metric_column). All still emit only whitelisted SQL shapes — no free text ever
reaches the generated SQL beyond a filter's own literal value, itself validated upstream in
pipeline_plan.py against the column's real profiled distinct values before it ever reaches here."""
from app.services.superset_templates import WHITELISTED_AGGREGATIONS

WHITELISTED_TIME_GRAINS = ("year", "month", "day")
FILTER_OPS = ("=", "!=", "IN", "IS_NULL", "IS_NOT_NULL")
DERIVED_OPS = ("column", "date_diff")
DATE_DIFF_UNITS = ("day", "month", "year")

_TIME_GRAIN_EXPR = {
    # All three grains truncate to a real DATE/TIMESTAMP, never an INTEGER — a "year" bucket
    # cast to ::int (the original form) is invisible to gold_profile's role detector
    # (connections._infer_column_role only classifies Date/DateTime/Time as "temporal"), which
    # silently locks every temporal-requiring chart type (trends, period comparisons...) out of
    # the AI's capability sheet for any gold aggregated at yearly grain.
    "year": "DATE_TRUNC('year', {col})",
    "month": "DATE_TRUNC('month', {col})",
    "day": "DATE_TRUNC('day', {col})",
}


class GoldBuilderError(Exception):
    pass


def _sql_literal(value) -> str:
    """Single-quoted SQL string literal, with the one escaping rule that actually matters here
    (a literal apostrophe) — never string-formats a whole clause, only ever this one value."""
    return "'" + str(value).replace("'", "''") + "'"


def build_filter_sql(filters: list[dict]) -> str:
    """filters: [{"column", "op", "value"}], op ∈ FILTER_OPS — already validated (lineage,
    op whitelist, value-against-profile) by pipeline_plan.py before this ever runs. Returns the
    bare condition text (no leading WHERE), ANDed — §3.1 deliberately has no OR in this version."""
    clauses = []
    for f in filters:
        column, op = f["column"], f["op"]
        if op == "IS_NULL":
            clauses.append(f"{column} IS NULL")
        elif op == "IS_NOT_NULL":
            clauses.append(f"{column} IS NOT NULL")
        elif op == "IN":
            values = f["value"] if isinstance(f["value"], list) else [f["value"]]
            clauses.append(f"{column} IN ({', '.join(_sql_literal(v) for v in values)})")
        else:  # "=" / "!="
            clauses.append(f"{column} {op} {_sql_literal(f['value'])}")
    return " AND ".join(clauses)


def _date_diff_expr(start: str, end: str, unit: str) -> str:
    if unit == "day":
        return f"({end} - {start})"
    if unit == "month":
        return f"((DATE_PART('year', {end}) - DATE_PART('year', {start})) * 12 + (DATE_PART('month', {end}) - DATE_PART('month', {start})))"
    return f"(DATE_PART('year', {end}) - DATE_PART('year', {start}))"  # "year"


def _metric_expr(metric_column: str, metric: dict | None) -> tuple[str, str]:
    """Returns (SQL expression to aggregate, identifier used for the output alias). §3.3 —
    metric_column is the flat, rétrocompat case (op="column" implicitly); metric={"op":
    "date_diff", ...} is the only derived op so far. Mutual exclusivity and column-lineage are
    pipeline_plan.py's job (it knows the real upstream schema, this module doesn't) — by the
    time this runs, both are trusted."""
    if metric and metric.get("op") == "date_diff":
        start, end, unit = metric["start"], metric["end"], metric.get("unit", "day")
        if unit not in DATE_DIFF_UNITS:
            raise GoldBuilderError(f"Unité de date_diff non autorisée : « {unit} » (attendu : {', '.join(DATE_DIFF_UNITS)}).")
        return _date_diff_expr(start, end, unit), f"date_diff_{start}_{end}"
    if not metric_column:
        raise GoldBuilderError("« metric_column » ou « metric » requis.")
    return metric_column, metric_column.lower()


def _agg_expr(aggregation: str, column_expr: str) -> str:
    if aggregation not in WHITELISTED_AGGREGATIONS:
        raise GoldBuilderError(f"Agrégation non autorisée : « {aggregation} » (attendu : {', '.join(WHITELISTED_AGGREGATIONS)}).")
    return f"COUNT(DISTINCT {column_expr})" if aggregation == "COUNT_DISTINCT" else f"{aggregation}({column_expr})"


def _aggregate_spec_expr(spec: dict) -> str:
    """§3.2 — one side (numerator or denominator) of a RATIO: its own aggregation/metric, with
    its own optional filter turned into a conditional aggregate (`CASE WHEN ... THEN col END`)
    rather than a subquery — a single pass, and simpler for sqlglot to validate downstream."""
    column_expr, _ = _metric_expr(spec.get("metric_column", ""), spec.get("metric"))
    filters = spec.get("filters") or []
    if filters:
        column_expr = f"CASE WHEN {build_filter_sql(filters)} THEN {column_expr} END"
    return _agg_expr(spec["aggregation"], column_expr)


def gold_output_columns(
    metric_column: str,
    dimension_columns: list[str],
    time_column: str | None,
    time_grain: str | None,
    *,
    aggregation: str | None = None,
    metric: dict | None = None,
) -> list[str]:
    """The exact column names `build_gold_sql` aliases its SELECT to — the single source of
    truth both the SQL builder and _resolve_tests (pipeline_plan.py) key off of, so a test
    referencing a gold column (e.g. the metric) can be validated/corrected against what the
    mart actually exposes rather than the raw metric_column name the AI was given."""
    cols = []
    if time_column:
        cols.append(f"{time_grain}_{time_column}")
    cols.extend(dimension_columns)
    if aggregation == "RATIO":
        cols.append("ratio")
    else:
        _, identifier = _metric_expr(metric_column, metric)
        cols.append(f"total_{identifier}")
    return cols


def build_gold_sql(
    upstream_model: str,
    metric_column: str,
    aggregation: str,
    dimension_columns: list[str],
    time_column: str | None,
    time_grain: str | None,
    *,
    metric: dict | None = None,
    filters: list[dict] | None = None,
    numerator: dict | None = None,
    denominator: dict | None = None,
    scale: float | None = None,
) -> str:
    if time_column and time_grain not in WHITELISTED_TIME_GRAINS:
        raise GoldBuilderError(f"Granularité temporelle non autorisée : « {time_grain} » (attendu : {', '.join(WHITELISTED_TIME_GRAINS)}).")

    select_cols: list[str] = []
    group_by_exprs: list[str] = []

    if time_column:
        time_expr = _TIME_GRAIN_EXPR[time_grain].format(col=time_column)
        select_cols.append(f"{time_expr} AS {time_grain}_{time_column}")
        group_by_exprs.append(time_expr)

    for dim in dimension_columns:
        select_cols.append(dim)
        group_by_exprs.append(dim)

    if aggregation == "RATIO":
        if not numerator or not denominator:
            raise GoldBuilderError("« RATIO » requiert un « numerator » et un « denominator ».")
        num_expr, den_expr = _aggregate_spec_expr(numerator), _aggregate_spec_expr(denominator)
        # §6 — NULLIF systématique : un dénominateur nul rend NULL, jamais une erreur
        # d'exécution ("division by zero"). Cast en ::float côté numérateur uniquement : suffit
        # à faire flotter toute la division en Postgres.
        scale_expr = f" * {scale:g}" if scale else ""
        select_cols.append(f"({num_expr})::float / NULLIF({den_expr}, 0){scale_expr} AS ratio")
    else:
        column_expr, identifier = _metric_expr(metric_column, metric)
        select_cols.append(f"{_agg_expr(aggregation, column_expr)} AS total_{identifier}")

    lines = ["SELECT " + select_cols[0]] + [f"    , {c}" for c in select_cols[1:]]
    lines.append(f"FROM {{{{ ref('{upstream_model}') }}}}")
    if filters:
        lines.append(f"WHERE {build_filter_sql(filters)}")
    if group_by_exprs:
        lines.append("GROUP BY " + ", ".join(group_by_exprs))
    return "\n".join(lines)
