"""add medallion tables

Revision ID: 644a3ac94065
Revises: 7c2779096efe
Create Date: 2026-07-09 22:03:03.050037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '644a3ac94065'
down_revision: Union[str, None] = '7c2779096efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medallion_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_store_source_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_source_id', sa.Integer(), nullable=False),
    sa.Column('airflow_stack_id', sa.Integer(), nullable=False),
    sa.Column('dbt_project_name', sa.String(length=120), nullable=False),
    sa.Column('target', sa.Enum('dev', 'prod', name='medallion_project_target'), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('dag_id', sa.String(length=200), nullable=True),
    sa.Column('dag_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'built', 'deployed', 'paused', 'error', name='medallion_project_status'), nullable=False),
    sa.Column('has_pending_changes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['airflow_stack_id'], ['infra_stacks.id'], ),
    sa.ForeignKeyConstraint(['object_store_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['warehouse_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medallion_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Enum('bronze', 'silver', 'gold', name='medallion_layer'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_object', sa.String(length=255), nullable=True),
    sa.Column('load_mode', sa.Enum('full', 'incremental', 'append', name='medallion_load_mode'), nullable=True),
    sa.Column('incremental_key', sa.String(length=120), nullable=True),
    sa.Column('partition_by', sa.String(length=120), nullable=True),
    sa.Column('bronze_location', sa.String(length=500), nullable=True),
    sa.Column('dbt_model_name', sa.String(length=120), nullable=True),
    sa.Column('materialization', sa.Enum('view', 'table', 'incremental', name='medallion_materialization'), nullable=True),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('upstream_dataset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_row_count', sa.Integer(), nullable=True),
    sa.Column('last_loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.Enum('none', 'passed', 'failed', name='medallion_test_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['medallion_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medallion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dag_run_id', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('queued', 'running', 'success', 'failed', name='medallion_run_state'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('layer_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tests_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logs_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['medallion_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medallion_runs')
    op.drop_table('medallion_datasets')
    op.drop_table('medallion_projects')
    # ### end Alembic commands ###
