"""add data_sources.last_tested_at

Revision ID: 7c2779096efe
Revises: 94ddd5a454f3
Create Date: 2026-07-09 19:09:19.164912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2779096efe'
down_revision: Union[str, None] = '94ddd5a454f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'last_tested_at')
    # ### end Alembic commands ###
