"""add contract_version to dashboard_specs

Revision ID: 8ff94c4a95d9
Revises: b10d5a740ea2
Create Date: 2026-08-16 01:05:59.538182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff94c4a95d9'
down_revision: Union[str, None] = 'b10d5a740ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_specs', sa.Column('contract_version', sa.String(length=10), server_default='flat', nullable=False))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping several indexes on unrelated tables — same
    # pre-existing model/DB drift noted in earlier migrations (f482ec661804, 724275be02e6,
    # b10d5a740ea2), unrelated to this one, so left out.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_specs', 'contract_version')
    # ### end Alembic commands ###
