"""add servers, infra_stacks, data_sources

Revision ID: 94ddd5a454f3
Revises: e5e2b7317222
Create Date: 2026-07-09 09:56:55.925545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94ddd5a454f3'
down_revision: Union[str, None] = 'e5e2b7317222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=120), nullable=False),
    sa.Column('auth_method', sa.Enum('key', 'password', name='server_auth_method'), nullable=False),
    sa.Column('secret_encrypted', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'reachable', 'unreachable', name='server_status'), nullable=False),
    sa.Column('docker_version', sa.String(length=64), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infra_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compose_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'deploying', 'running', 'stopped', 'error', name='stack_status'), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('postgresql', 'minio', 'oracle', 'mysql', name='data_source_type'), nullable=False),
    sa.Column('origin', sa.Enum('platform', 'external', name='data_source_origin'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_encrypted', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'reachable', 'unreachable', name='data_source_status'), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['infra_stacks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_sources')
    op.drop_table('infra_stacks')
    op.drop_table('servers')
    # ### end Alembic commands ###
