"""add source_relationships table

Revision ID: b10d5a740ea2
Revises: 724275be02e6
Create Date: 2026-08-14 21:25:59.339237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10d5a740ea2'
down_revision: Union[str, None] = '724275be02e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('child_table', sa.String(length=255), nullable=False),
    sa.Column('child_column', sa.String(length=255), nullable=False),
    sa.Column('parent_table', sa.String(length=255), nullable=False),
    sa.Column('parent_column', sa.String(length=255), nullable=False),
    sa.Column('match_rate', sa.Float(), nullable=False),
    sa.Column('distinct_child', sa.Integer(), nullable=False),
    sa.Column('distinct_parent', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('basis', sa.String(length=50), nullable=False),
    sa.Column('schema_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'child_table', 'child_column', 'parent_table', 'parent_column', name='uq_source_relationship_pair')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping several indexes on unrelated tables (data
    # quality, versions, notification channels) — same pre-existing model/DB drift noted in
    # f482ec661804 and 724275be02e6's own migrations, unrelated to this one, so left out.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_relationships')
    # ### end Alembic commands ###
