"""add ml transform fields to medallion_datasets

Revision ID: d8be9d685eb4
Revises: 644a3ac94065
Create Date: 2026-07-10 23:11:31.809010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8be9d685eb4'
down_revision: Union[str, None] = '644a3ac94065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


transform_type_enum = sa.Enum('dbt', 'python', name='medallion_transform_type')
ml_objective_enum = sa.Enum('none', 'anomaly', 'scoring', 'forecast', 'clustering', name='medallion_ml_objective')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    transform_type_enum.create(bind, checkfirst=True)
    ml_objective_enum.create(bind, checkfirst=True)
    op.add_column('medallion_datasets', sa.Column('transform_type', transform_type_enum, nullable=False, server_default='dbt'))
    op.add_column('medallion_datasets', sa.Column('ml_objective', ml_objective_enum, nullable=False, server_default='none'))
    op.add_column('medallion_datasets', sa.Column('python_code', sa.Text(), nullable=True))
    op.add_column('medallion_datasets', sa.Column('template_id', sa.Integer(), nullable=True))
    op.add_column('medallion_datasets', sa.Column('output_table', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medallion_datasets', 'output_table')
    op.drop_column('medallion_datasets', 'template_id')
    op.drop_column('medallion_datasets', 'python_code')
    op.drop_column('medallion_datasets', 'ml_objective')
    op.drop_column('medallion_datasets', 'transform_type')
    bind = op.get_bind()
    ml_objective_enum.drop(bind, checkfirst=True)
    transform_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
