"""add semantic_annotations table

Revision ID: f482ec661804
Revises: d3774eb751a7
Create Date: 2026-08-11 22:50:42.839569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f482ec661804'
down_revision: Union[str, None] = 'd3774eb751a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'table_name', 'column_name', name='uq_semantic_annotation_source_table_column')
    )
    op.create_index('uq_semantic_annotation_source_table_null_column', 'semantic_annotations', ['data_source_id', 'table_name'], unique=True, postgresql_where=sa.text('column_name IS NULL'))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping several indexes on unrelated tables
    # (data_quality_alerts/snapshots, medallion_versions, notification_channels) — pre-existing
    # drift between the models and the live DB, unrelated to this migration. Intentionally
    # left untouched here to keep this migration scoped to semantic_annotations only.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_semantic_annotation_source_table_null_column', table_name='semantic_annotations', postgresql_where=sa.text('column_name IS NULL'))
    op.drop_table('semantic_annotations')
    # ### end Alembic commands ###
