"""Chart template library (Module 12 étape 1, extended by the "Annexe catalogue viz") —
captured by hand, once, against the real Superset image provisioned by Module 1 (apache/
superset 6.1.0 + psycopg2-binary), per the spec's explicit instruction: `params`/
`query_context` are undocumented and version-sensitive, so nothing here is guessed or
generated by Mistral. Each viz_type was built through the real Explore UI (or, for the
annexe's additions — see `extended.py` — verified via a direct create/fetch-back round trip
against the live instance, since no browser access was available for this batch; each such
function says so in its own docstring), then captured/confirmed via `GET /api/v1/chart/{id}`.

Two structural findings from that capture, both load-bearing:
  - a "groupby"/"dimensions" field takes a list of plain column-name STRINGS, never full
    column objects (using full objects there renders "DB engine Error: Missing label").
  - a "metric"/"metrics" field takes full adhoc-metric dicts (column object + aggregate).
`query_context` is deliberately not built here — Superset derives it correctly server-side
from a correct `params`, confirmed empirically (see Module 12 build notes).

This package is now the catalogue-driven home for the chart template library: `chart_catalog.json`
(the source of truth for which viz_type are proposable at all, per the annexe spec) lives
alongside this file. `TEMPLATE_REGISTRY` maps every viz_type that has a REAL, verified
template function to that function — `services/chart_catalog.py`'s capability sheet only ever
exposes a viz_type to the AI if it's both `status=active` in the catalogue AND present here,
so the AI can never be offered a type this package doesn't actually know how to build.
"""
from dataclasses import dataclass

# Deliberately restricted catalogue (Module 12 §3.3), now sourced from chart_catalog.json via
# services/chart_catalog.py rather than hard-coded here — kept as a fallback/compat constant
# for any caller still importing it directly (e.g. sql_validator-style whitelists elsewhere).
WHITELISTED_VIZ_TYPES = ("big_number_total", "echarts_timeseries_line", "echarts_timeseries_bar", "pie", "table")
WHITELISTED_AGGREGATIONS = ("SUM", "AVG", "COUNT", "COUNT_DISTINCT", "MIN", "MAX")


@dataclass
class MetricSpec:
    column: dict  # full Superset column object, as reflected by the dataset (has id/uuid/type)
    aggregate: str  # one of WHITELISTED_AGGREGATIONS


def _metric_dict(metric: MetricSpec, option_suffix: str) -> dict:
    label = f"{metric.aggregate}({metric.column['column_name']})"
    return {
        "expressionType": "SIMPLE",
        "column": metric.column,
        "aggregate": metric.aggregate,
        "sqlExpression": None,
        "datasourceWarning": False,
        "hasCustomLabel": False,
        "label": label,
        "optionName": f"metric_{option_suffix}",
    }


def big_number_total(datasource: str, metric: MetricSpec) -> dict:
    """A single KPI — one aggregated measure, no dimension."""
    return {
        "datasource": datasource,
        "viz_type": "big_number_total",
        "metric": _metric_dict(metric, "kpi"),
        "adhoc_filters": [],
        "header_font_size": 0.4,
        "subtitle_font_size": 0.15,
        "show_metric_name": False,
        "metric_name_font_size": 0.15,
        "y_axis_format": "SMART_NUMBER",
        "time_format": "smart_date",
        "force_timestamp_formatting": False,
        "extra_form_data": {},
    }


def echarts_timeseries(viz_type: str, datasource: str, x_axis: str, metric: MetricSpec, groupby: list[str]) -> dict:
    """Shared by echarts_timeseries_line (trend over time) and echarts_timeseries_bar
    (comparison across categories) — same modern ECharts control family in this Superset
    version; `x_axis` is a plain column name, temporal or categorical either way."""
    params = {
        "datasource": datasource,
        "viz_type": viz_type,
        "x_axis": x_axis,
        "time_grain_sqla": "P1D",
        "xAxisForceCategorical": False,
        "x_axis_sort_asc": True,
        "metrics": [_metric_dict(metric, "series")],
        "groupby": groupby,
        "adhoc_filters": [],
        "order_desc": True,
        "row_limit": 10000,
        "truncate_metric": True,
        "show_empty_columns": True,
        "comparison_type": "values",
        "annotation_layers": [],
        "forecastEnabled": False,
        "x_axis_title": "",
        "y_axis_title": "",
        "color_scheme": "supersetColors",
        "show_value": False,
        "show_legend": True,
        "legendType": "scroll",
        "legendOrientation": "top",
        "x_axis_time_format": "smart_date",
        "y_axis_format": "SMART_NUMBER",
        "rich_tooltip": True,
        "tooltipTimeFormat": "smart_date",
        "extra_form_data": {},
    }
    if viz_type == "echarts_timeseries_bar":
        params["orientation"] = "vertical"
    return params


def pie(datasource: str, groupby: list[str], metric: MetricSpec) -> dict:
    """A single dimension's share of one measure — low-cardinality breakdown."""
    return {
        "datasource": datasource,
        "viz_type": "pie",
        "groupby": groupby,
        "metric": _metric_dict(metric, "pie"),
        "adhoc_filters": [],
        "row_limit": 100,
        "sort_by_metric": True,
        "color_scheme": "supersetColors",
        "show_labels_threshold": 5,
        "show_legend": True,
        "legendType": "scroll",
        "legendOrientation": "top",
        "label_type": "key",
        "number_format": "SMART_NUMBER",
        "date_format": "smart_date",
        "show_labels": True,
        "labels_outside": True,
        "outerRadius": 70,
        "donut": False,
        "innerRadius": 30,
        "extra_form_data": {},
    }


def table(datasource: str, groupby: list[str], metrics: list[MetricSpec]) -> dict:
    """Tabular detail — dimensions + raw aggregated measures, no chart geometry."""
    return {
        "datasource": datasource,
        "viz_type": "table",
        "query_mode": "aggregate",
        "groupby": groupby,
        "metrics": [_metric_dict(m, f"col{i}") for i, m in enumerate(metrics)],
        "all_columns": [],
        "percent_metrics": [],
        "adhoc_filters": [],
        "order_by_cols": [],
        "order_desc": True,
        "server_pagination": False,
        "server_page_length": 10,
        "row_limit": 1000,
        "percent_metric_calculation": "row_limit",
        "show_totals": False,
        "table_timestamp_format": "smart_date",
        "include_search": False,
        "allow_rearrange_columns": False,
        "allow_render_html": True,
        "show_cell_bars": True,
        "align_pn": False,
        "color_pn": True,
        "extra_form_data": {},
    }


# Annexe catalogue viz §7 — every viz_type below has a real, verified template function.
# services/chart_catalog.py's capability sheet intersects the JSON catalogue's `active`
# entries with this registry's keys, so a type is only ever offered to the AI once it's
# actually here — never guessed ahead of being captured/verified.
from app.services.superset_templates.extended import EXTENDED_TEMPLATES  # noqa: E402

# Every slot in `slots` below is ALWAYS a list (list[MetricSpec] for measure-role slots,
# list[str] otherwise) regardless of the catalogue's own min/max cardinality for that slot —
# a uniform, information-preserving shape built once by superset_publish._resolve_slots_for_template.
# Each lambda here is the only place that knows whether ITS OWN Superset params field wants a
# scalar (indexed with [0]) or the list as-is — that mapping is real Superset UI knowledge, not
# derivable from the catalogue, so it is hard-coded per viz_type, never inferred generically.
TEMPLATE_REGISTRY = {
    "big_number_total": lambda datasource, slots: big_number_total(datasource, slots["metric"][0]),
    "echarts_timeseries_line": lambda datasource, slots: echarts_timeseries("echarts_timeseries_line", datasource, slots["x_axis"][0], slots["metrics"][0], slots.get("groupby", [])),
    "echarts_timeseries_bar": lambda datasource, slots: echarts_timeseries("echarts_timeseries_bar", datasource, slots["x_axis"][0], slots["metrics"][0], slots.get("groupby", [])),
    "pie": lambda datasource, slots: pie(datasource, slots["groupby"], slots["metric"][0]),
    "table": lambda datasource, slots: table(datasource, slots.get("groupby", []), slots.get("metrics", [])),
    **EXTENDED_TEMPLATES,
}
